---
- name: Check Int description
  hosts: xr-all
  gather_facts: false
  connection: local

  tasks:
    - name: show commands are running
      iosxr_command:
        commands:
          - sh int descr | i up
          - sh ip int br | i up
          - show run int 
          - sh run group core-interface

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

#Commands to run:
# ansible-playbook ios-xr_sh_int.yaml -u akahric -k
# 1.)Please change to your username and use your radius password when prompted
# 2.)Please move to output directory to see the results of all commands 
