- name: Push configuration to CiscoSandbox ASR9k
  hosts: xr-sandbox
  gather_facts: false
  connection: local

  tasks:
    - name: Configure QOS Class-Map from file 
      cisco.iosxr.iosxr_config:
        src: qos_core.cfg
        replace: line
        backup: yes

      register: print_output

    -  debug: var=print_output.stdout_lines


# Commands to run:
#1) ansible-playbook ios-xr_conf_qos_core.yaml-u akahric -k
# !!Please use Radius paassword when prompted.
