---
- name: Check L2vpn config and operations
  hosts: xr-9k
  gather_facts: false
  connection: local

  tasks:
    - name: show commands are running 
      iosxr_command:
        commands:
          - sh run l2vpn
          - sh l2vpn xconnect
          - sh bgp l2vpn vpws neighbors brief
          - sh bgp l2vpn vpws
          - sh l2vpn xconnect detail


      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook ios-xr_sh_vpws.yaml -u akahric -k
# !!Please change to your username and use your radius password when prompted
