- name: Push VRRP configurtion commands to IOS XR
  hosts: xr-sandbox
  gather_facts: false
  connection: local

  tasks:
    - name: configuration commands are running
      cisco.iosxr.iosxr_config:
        lines:
        - name my-ansible-master
        - priority 130
        - address 7.7.7.7
        - address 9.9.9.9 secondary
        parents:
        - router vrrp 
        - interface TenGigE0/0/0/3.130
        - address-family ipv4
        - vrrp 130

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook xr_config_bgp_lines.yaml -u cisco -k
# !!Please change to your username and use your radius password when prompted
