---
- name: Check L2vpn config and operations
  hosts: xr-9k
  gather_facts: false
  connection: local

  tasks:
    - name: show commands are running 
      iosxr_command:
        commands:
          - sh run l2vpn
          - show l2vpn xconnect	
          - sh l2vpn forw summary location 0/0/CPU0 


      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook ios-xr_sh_l2vpn.yaml -u akahric -k
# !!Please change to your username and use your radius password when prompted
