- name: Push configuration on IOS-XRv 9000Sandbox
  hosts: xr-sandbox
  gather_facts: false
  connection: local

  tasks:
    - name: Configure BGP & VRF 
      cisco.iosxr.iosxr_config:
        lines:
        - import route-target 1:100
        - export route-target 1:100
        parents:
        - vrf CUST_100500
        - address-family ipv4 unicast

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: BGP / VRF / create and configure IPv4 UNI AF
      cisco.iosxr.iosxr_config:
        lines:
        - redistribute connected
        parents:
        - router bgp 1
        - neighbor 192.168.255.250 remote-as 1
        - address-family ipv4 unicast

    - name: save output to a file
      lineinfile:
        create: yes
        line: "{{item}}"
        path: ./output/{{ inventory_hostname }}.txt
      with_items: "{{ print_output.stdout }}"

# Commands to run:
#1) ansible-playbook xr_sandbox_conf_bgp_vrf_parent_lines.yaml -u admin -k
# !!Please use the  following password C1sco12345 when prompted
